name: CI

on:
  push:
    branches: ["**"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: pip install uv

      - name: Install dependencies
        uses: uv sync

      - name: Install ruff and mypy
        uses: uv pip install ruff mypy

      - name: Ruff format
        uses: uv run ruff format . --check

      - name: Ruff linter
        uses: uv run ruff check . --fix

      - name: Mypy
        uses: uv run mypy .

      - name: Unit tests
        uses: uv run pytest ./core/test/unit

      - name: Integration tests
        uses: uv run pytest ./core/test/integration

      - name: BDD tests
        uses: uv run pytest ./core/test/behaviour